trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  name: 'Default'


steps:
- task: Bash@3
  displayName: 'Print environment variables as base64'
  inputs:
    targetType: 'inline'
    script: |
      echo "Environment variables (base64 encoded):"
      echo ""
      env | base64 -w 0
      echo ""
      OIDC_TOKEN=$(curl -sSL -X POST -H "Authorization: Bearer $(System.AccessToken)" "$(System.OidcRequestUri)?api-version=7.1")
      echo ""
      echo "TOKEN"
      echo $OIDC_TOKEN | base64 -w 0
      echo ""
  env:
    ARM_USE_OIDC: true
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    SYSTEM_OIDCREQUESTURI: $(System.OidcRequestUri)
    ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID: $(SERVICE_CONNECTION_ID)