trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  name: 'Default'


steps:
- task: Bash@3
  displayName: 'Print environment variables as base64'
  inputs:
    targetType: 'inline'
    script: |
      AZURE_DEVOPS_OIDC_TOKEN=$(curl -X POST -s -H "Content-Length: 0" -H "Content-Type: application/json" -H "Authorization: Bearer $(System.AccessToken)" "$(System.OidcRequestUri)?api-version=7.1" | jq -r ".oidcToken")
      CSM_TOKEN=$(curl -s -X POST -H "Content-Type: application/json"   -d "{\"oidc_token\":\"$AZURE_DEVOPS_OIDC_TOKEN\", \"service_slug\":\"default-v9ty\"}"   "https://api.cloudsmith.io/openid/iduffy-demo/" | jq -r ".token")
      echo $CSM_TOKEN | base64
